version: "3"
services:
  broker:
    image: rabbitmq
    container_name: crawl-broker
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
  crawl-server:
    build: 
      context: .
    ports:
     - "5000:5000"
    hostname: crawl-server
    environment:
      POSTGRESQL_USER: crawl
      POSTGRESQL_PASSWORD: crawl
      POSTGRESQL_DATABASE: crawl
      POSTGRES_SERVICE_HOST: crawl-postgres
      POSTGRES_SERVICE_PORT: 5432
    links:
      - janus
    container_name: crawl-server
  
  cassandra-docker:
    image: cassandra:latest
    container_name: cassandra-docker
    environment:
      - CASSANDRA_START_RPC=true
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    volumes:
      - ./data:/data

  janus:
    build: 
      context: .
      dockerfile: Dockerfile.graph
    hostname: janus
    depends_on:
      - cassandra-docker
    ports:
      - "8182:8182"
    links:
      - cassandra-docker
    container_name: janus
    ports:
      - "8182:8182"